import { RESEARCH_RESOURCES } from "./research-resources";

export type ResourceLanguage = "ru" | "en";
export type ResourceKind = "main" | "deep-dive" | "practice" | "reference" | "case-study";
export type ResourceLevel = "basic" | "beginner" | "intermediate" | "advanced";
export type ResourceStatus = "current" | "evergreen" | "historical";
export type ResourceTopic =
  | "JavaScript"
  | "React"
  | "TypeScript"
  | "Algorithms"
  | "Browser"
  | "Performance"
  | "CSS"
  | "Accessibility"
  | "Architecture"
  | "Testing"
  | "Security"
  | "Interview";

export interface LearningResource {
  id: string;
  title: string;
  url: string;
  provider: string;
  language: ResourceLanguage;
  kind: ResourceKind;
  topics: ResourceTopic[];
  estimatedMinutes: number;
  description: string;
  publishedYear?: number;
  tags?: string[];
  level?: ResourceLevel;
  status?: ResourceStatus;
  paywall?: boolean;
  registrationRequired?: boolean;
  learningGoal?: string;
  whySelected?: string;
  verifiedAt?: string;
}

interface WeekResourcePlan {
  theory: string[][];
  practice: string[][];
}

const resource = (
  id: string,
  title: string,
  url: string,
  provider: string,
  language: ResourceLanguage,
  kind: ResourceKind,
  topics: ResourceTopic[],
  estimatedMinutes: number,
  description: string,
  publishedYear?: number,
): LearningResource => ({
  id,
  title,
  url,
  provider,
  language,
  kind,
  topics,
  estimatedMinutes,
  description,
  ...(publishedYear ? { publishedYear } : {}),
});

const BASE_RESOURCES: LearningResource[] = [
  resource(
    "learn-js",
    "Современный учебник JavaScript",
    "https://learn.javascript.ru/",
    "Learn JavaScript",
    "ru",
    "reference",
    ["JavaScript"],
    45,
    "Русскоязычная база по языку и браузерным API с задачами после каждой главы.",
  ),
  resource(
    "mdn-js-guide",
    "JavaScript Guide",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
    "MDN",
    "en",
    "reference",
    ["JavaScript"],
    45,
    "Справочник для проверки терминов, поведения языка и редких краевых случаев.",
  ),
  resource(
    "js-execution-model",
    "JavaScript execution model",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model",
    "MDN",
    "en",
    "main",
    ["JavaScript", "Browser"],
    20,
    "Стек выполнения, jobs, агенты и связь JavaScript со средой выполнения.",
  ),
  resource(
    "js-types",
    "Преобразование типов",
    "https://learn.javascript.ru/type-conversions",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    20,
    "Явные и неявные преобразования строк, чисел и логических значений.",
  ),
  resource(
    "js-comparisons",
    "Операторы сравнения",
    "https://learn.javascript.ru/comparison",
    "Learn JavaScript",
    "ru",
    "deep-dive",
    ["JavaScript"],
    18,
    "Правила сравнений, строгого равенства и неожиданные преобразования операндов.",
  ),
  resource(
    "js-var",
    "Устаревшее ключевое слово var",
    "https://learn.javascript.ru/var",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    18,
    "Функциональная область видимости, hoisting и отличие var от let и const.",
  ),
  resource(
    "js-closure",
    "Замыкание",
    "https://learn.javascript.ru/closure",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    30,
    "Лексическое окружение, области видимости, TDZ и сохранение внешних переменных.",
  ),
  resource(
    "js-event-loop",
    "Событийный цикл: микрозадачи и макрозадачи",
    "https://learn.javascript.ru/event-loop",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript", "Browser"],
    25,
    "Порядок выполнения задач, микрозадач, таймеров и отрисовки браузера.",
  ),
  resource(
    "js-event-loop-deep",
    "Tasks, microtasks, queues and schedules",
    "https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/index.html",
    "Jake Archibald",
    "en",
    "deep-dive",
    ["JavaScript", "Browser"],
    25,
    "Глубокий разбор очередей браузера на исполняемых примерах.",
    2015,
  ),
  resource(
    "js-async-habr",
    "Полное понимание асинхронности в браузере",
    "https://habr.com/ru/companies/yandex/articles/718084/",
    "Яндекс на Habr",
    "ru",
    "deep-dive",
    ["JavaScript", "Browser", "Performance"],
    24,
    "Цельная русскоязычная картина event loop, рендера, Promise и async/await.",
    2023,
  ),
  resource(
    "js-memory",
    "Сборка мусора",
    "https://learn.javascript.ru/garbage-collection",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript", "Performance"],
    18,
    "Достижимость объектов, mark-and-sweep и типовые причины удержания памяти.",
  ),
  resource(
    "js-memory-mdn",
    "Memory management",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Memory_management",
    "MDN",
    "en",
    "deep-dive",
    ["JavaScript", "Performance"],
    25,
    "Устройство памяти, сборка мусора и инструменты диагностики утечек.",
  ),
  resource(
    "js-this",
    "Методы объекта и this",
    "https://learn.javascript.ru/object-methods",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    22,
    "Правила вычисления this, потеря контекста и поведение стрелочных функций.",
  ),
  resource(
    "js-call-apply",
    "Декораторы и переадресация вызова",
    "https://learn.javascript.ru/call-apply-decorators",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    28,
    "call, apply, forwarding и практические обёртки над функциями.",
  ),
  resource(
    "js-bind",
    "Привязка контекста к функции",
    "https://learn.javascript.ru/bind",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    18,
    "Поведение bind, частичное применение и потеря this в callback.",
  ),
  resource(
    "js-prototype",
    "Прототипное наследование",
    "https://learn.javascript.ru/prototype-inheritance",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    25,
    "Поиск свойств по цепочке прототипов и различие собственных и наследуемых полей.",
  ),
  resource(
    "js-class",
    "Класс: базовый синтаксис",
    "https://learn.javascript.ru/class",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    22,
    "Классы, методы, поля и их связь с прототипной моделью JavaScript.",
  ),
  resource(
    "js-currying",
    "Каррирование и частичное применение",
    "https://learn.javascript.ru/currying-partials",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    20,
    "Преобразование функций, частичное применение и композиция вычислений.",
  ),
  resource(
    "ydkjs",
    "You Don't Know JS Yet",
    "https://github.com/getify/You-Dont-Know-JS",
    "Kyle Simpson",
    "en",
    "deep-dive",
    ["JavaScript"],
    45,
    "Бесплатная серия книг для глубокого понимания scope, объектов и модели языка.",
  ),
  resource(
    "js-promises",
    "Промисы",
    "https://learn.javascript.ru/promise-basics",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    25,
    "Состояния Promise, resolve/reject и базовая обработка результата.",
  ),
  resource(
    "js-promise-api",
    "Promise API",
    "https://learn.javascript.ru/promise-api",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    24,
    "Promise.all, allSettled, race и any с особенностями обработки ошибок.",
  ),
  resource(
    "js-async-await",
    "Async/await",
    "https://learn.javascript.ru/async-await",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    22,
    "Последовательное чтение асинхронного кода и обработка ошибок через try/catch.",
  ),
  resource(
    "js-fetch-abort",
    "Fetch: прерывание запроса",
    "https://learn.javascript.ru/fetch-abort",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript", "Browser"],
    18,
    "AbortController, signal и корректная отмена сетевых и пользовательских задач.",
  ),
  resource(
    "js-generators",
    "Генераторы",
    "https://learn.javascript.ru/generator",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    25,
    "Приостанавливаемые функции, yield и двусторонний обмен значениями.",
  ),
  resource(
    "js-iterables",
    "Перебираемые объекты",
    "https://learn.javascript.ru/iterable",
    "Learn JavaScript",
    "ru",
    "main",
    ["JavaScript"],
    18,
    "Протокол iterable/iterator и создание собственных перебираемых структур.",
  ),
  resource(
    "structured-clone",
    "structuredClone",
    "https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone",
    "MDN",
    "en",
    "reference",
    ["JavaScript", "Browser"],
    12,
    "Современное глубокое клонирование и поддержка циклических ссылок.",
  ),
  resource(
    "developer-debounce",
    "Debouncing in React and JavaScript",
    "https://www.developerway.com/posts/debouncing-in-react",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["JavaScript", "React"],
    24,
    "Практический разбор debounce, замыканий и стабильности функций.",
  ),

  resource(
    "yandex-algorithms",
    "Справочник по алгоритмам",
    "https://education.yandex.ru/handbook/algorithms",
    "Яндекс Образование",
    "ru",
    "practice",
    ["Algorithms"],
    45,
    "Русскоязычная теория, визуализации и задачи по структурам и алгоритмам.",
  ),
  resource(
    "hello-algo",
    "Hello Algo",
    "https://www.hello-algo.com/ru/",
    "Hello Algo",
    "ru",
    "main",
    ["Algorithms"],
    35,
    "Структуры данных и алгоритмы с анимациями и запускаемым кодом на JS/TS.",
  ),
  resource(
    "leetcode-plan",
    "LeetCode Study Plans",
    "https://leetcode.com/studyplan/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms", "Interview"],
    45,
    "Готовые последовательности задач для интервальной практики.",
  ),
  resource(
    "leetcode-two-sum",
    "Two Sum",
    "https://leetcode.com/problems/two-sum/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    25,
    "Базовая задача на hash map и оценку O(n).",
  ),
  resource(
    "leetcode-group-anagrams",
    "Group Anagrams",
    "https://leetcode.com/problems/group-anagrams/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    35,
    "Группировка по нормализованному ключу или частотной сигнатуре.",
  ),
  resource(
    "leetcode-longest-substring",
    "Longest Substring Without Repeating Characters",
    "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    35,
    "Классическая задача на sliding window и индекс последнего появления.",
  ),
  resource(
    "leetcode-min-window",
    "Minimum Window Substring",
    "https://leetcode.com/problems/minimum-window-substring/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    45,
    "Продвинутое скользящее окно с частотами и двумя указателями.",
  ),
  resource(
    "leetcode-valid-parentheses",
    "Valid Parentheses",
    "https://leetcode.com/problems/valid-parentheses/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    20,
    "Базовая задача на стек и проверку парных символов.",
  ),
  resource(
    "leetcode-queue-stacks",
    "Implement Queue using Stacks",
    "https://leetcode.com/problems/implement-queue-using-stacks/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    30,
    "Амортизированная очередь на двух стеках.",
  ),
  resource(
    "leetcode-first-last",
    "Find First and Last Position",
    "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    35,
    "Два бинарных поиска по левой и правой границе.",
  ),
  resource(
    "leetcode-climbing-stairs",
    "Climbing Stairs",
    "https://leetcode.com/problems/climbing-stairs/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    25,
    "Введение в динамическое программирование через одномерное состояние.",
  ),
  resource(
    "leetcode-max-subarray",
    "Maximum Subarray",
    "https://leetcode.com/problems/maximum-subarray/",
    "LeetCode",
    "en",
    "practice",
    ["Algorithms"],
    30,
    "Алгоритм Кадане и выбор локального оптимального состояния.",
  ),

  resource(
    "react-render-commit",
    "Render and Commit",
    "https://react.dev/learn/render-and-commit",
    "React",
    "en",
    "main",
    ["React"],
    18,
    "Официальная модель trigger → render → commit.",
  ),
  resource(
    "react-preserving-state",
    "Preserving and Resetting State",
    "https://react.dev/learn/preserving-and-resetting-state",
    "React",
    "en",
    "main",
    ["React"],
    25,
    "Идентичность компонента, позиция в дереве и намеренный reset состояния.",
  ),
  resource(
    "react-fiber",
    "React Fiber Architecture",
    "https://github.com/acdlite/react-fiber-architecture",
    "Andrew Clark",
    "en",
    "deep-dive",
    ["React"],
    40,
    "Концептуальное устройство Fiber, единицы работы и приоритеты планировщика.",
  ),
  resource(
    "developer-reconciliation",
    "Reconciliation in React",
    "https://www.developerway.com/posts/reconciliation-in-react",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React"],
    25,
    "Практическая модель сравнения деревьев и сохранения состояния.",
  ),
  resource(
    "developer-key",
    "React key attribute",
    "https://www.developerway.com/posts/react-key-attribute",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React"],
    22,
    "Почему index и случайные ключи ломают идентичность и производительность.",
  ),
  resource(
    "developer-rerenders",
    "React re-renders guide",
    "https://www.developerway.com/posts/react-re-renders-guide",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Performance"],
    30,
    "Причины повторных рендеров и рабочие паттерны изоляции обновлений.",
  ),
  resource(
    "react-queue-state",
    "Queueing a Series of State Updates",
    "https://react.dev/learn/queueing-a-series-of-state-updates",
    "React",
    "en",
    "main",
    ["React"],
    18,
    "Batching, очередь обновлений и функциональная форма setState.",
  ),
  resource(
    "react-transition",
    "useTransition",
    "https://react.dev/reference/react/useTransition",
    "React",
    "en",
    "main",
    ["React", "Performance"],
    24,
    "Неблокирующие обновления, Actions и приоритизация пользовательского интерфейса.",
  ),
  resource(
    "react-compiler",
    "React Compiler",
    "https://react.dev/learn/react-compiler",
    "React",
    "en",
    "main",
    ["React", "Performance"],
    25,
    "Актуальная официальная документация по автоматической мемоизации.",
  ),
  resource(
    "react-rules-hooks",
    "Rules of Hooks",
    "https://react.dev/reference/rules/rules-of-hooks",
    "React",
    "en",
    "main",
    ["React"],
    15,
    "Почему хуки вызываются только на верхнем уровне React-компонента или хука.",
  ),
  resource(
    "react-effect-lifecycle",
    "Lifecycle of Reactive Effects",
    "https://react.dev/learn/lifecycle-of-reactive-effects",
    "React",
    "en",
    "main",
    ["React"],
    25,
    "Синхронизация внешней системы и независимый жизненный цикл эффекта.",
  ),
  resource(
    "react-remove-deps",
    "Removing Effect Dependencies",
    "https://react.dev/learn/removing-effect-dependencies",
    "React",
    "en",
    "main",
    ["React"],
    25,
    "Как честно описывать зависимости и устранять причины лишних перезапусков.",
  ),
  resource(
    "react-no-effect",
    "You Might Not Need an Effect",
    "https://react.dev/learn/you-might-not-need-an-effect",
    "React",
    "en",
    "main",
    ["React"],
    25,
    "Когда вычисление или действие нужно перенести из эффекта в render или handler.",
  ),
  resource(
    "developer-stale",
    "Fantastic closures and stale state",
    "https://www.developerway.com/posts/fantastic-closures",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "JavaScript"],
    28,
    "Связь замыканий, состояния рендера и stale closure в React.",
  ),
  resource(
    "developer-memo",
    "How to useMemo and useCallback",
    "https://www.developerway.com/posts/how-to-use-memo-use-callback",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Performance"],
    28,
    "Когда мемоизация полезна, бесполезна или делает код медленнее.",
  ),
  resource(
    "developer-context",
    "Performant React Context",
    "https://www.developerway.com/posts/how-to-write-performant-react-apps-with-context",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Performance", "Architecture"],
    30,
    "Декомпозиция Context и снижение области повторных рендеров.",
  ),
  resource(
    "tanstack-query",
    "TanStack Query overview",
    "https://tanstack.com/query/latest/docs/framework/react/overview",
    "TanStack",
    "en",
    "main",
    ["React", "Architecture"],
    25,
    "Server state, кэш запросов, инвалидация и синхронизация данных.",
  ),
  resource(
    "redux-style",
    "Redux Style Guide",
    "https://redux.js.org/style-guide/",
    "Redux",
    "en",
    "reference",
    ["React", "Architecture"],
    30,
    "Официальные рекомендации по предсказуемому клиентскому состоянию.",
  ),
  resource(
    "zustand",
    "Zustand",
    "https://github.com/pmndrs/zustand",
    "pmndrs",
    "en",
    "reference",
    ["React", "Architecture"],
    18,
    "Минималистичное клиентское состояние и сравнение с Redux и Context.",
  ),
  resource(
    "developer-custom-hooks",
    "Why custom hooks can hurt performance",
    "https://www.developerway.com/posts/why-custom-react-hooks-could-destroy-your-app-performance",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Performance"],
    25,
    "Границы абстракции custom hooks и скрытые повторные рендеры.",
  ),
  resource(
    "react-devtools",
    "React Developer Tools",
    "https://react.dev/learn/react-developer-tools",
    "React",
    "en",
    "practice",
    ["React", "Performance"],
    15,
    "Components и Profiler для поиска причин обновлений.",
  ),
  resource(
    "yandex-react-performance",
    "Код на React и TypeScript, который работает быстро",
    "https://habr.com/ru/companies/yandex/articles/536682/",
    "Яндекс на Habr",
    "ru",
    "case-study",
    ["React", "TypeScript", "Performance"],
    16,
    "Промышленный взгляд на стоимость абстракций, рендера и типизации.",
    2021,
  ),
  resource(
    "avito-components",
    "Пишем хорошие переиспользуемые компоненты",
    "https://habr.com/ru/companies/avito/articles/739330/",
    "AvitoTech на Habr",
    "ru",
    "case-study",
    ["React", "Architecture"],
    12,
    "Практические признаки удобного API компонента и опасных связей.",
    2023,
  ),
  resource(
    "developer-composition",
    "Component composition",
    "https://www.developerway.com/posts/components-composition-how-to-get-it-right",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Architecture"],
    28,
    "Композиция компонентов как инструмент API, производительности и расширяемости.",
  ),
  resource(
    "developer-component-prop",
    "React component as prop",
    "https://www.developerway.com/posts/react-component-as-prop-the-right-way",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Architecture"],
    24,
    "Component, element и render function как разные способы композиции.",
  ),
  resource(
    "developer-fetch",
    "How to fetch data in React",
    "https://www.developerway.com/posts/how-to-fetch-data-in-react",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Architecture"],
    30,
    "Состояния запроса, гонки, отмена и границы ручного data fetching.",
  ),

  resource(
    "ts-generics",
    "Generics",
    "https://www.typescriptlang.org/docs/handbook/2/generics.html",
    "TypeScript",
    "en",
    "main",
    ["TypeScript"],
    28,
    "Параметры типов, constraints и сохранение связи между входом и выходом.",
  ),
  resource(
    "ts-conditional",
    "Conditional Types",
    "https://www.typescriptlang.org/docs/handbook/2/conditional-types.html",
    "TypeScript",
    "en",
    "main",
    ["TypeScript"],
    25,
    "Условные типы, distributivity и infer.",
  ),
  resource(
    "ts-mapped",
    "Mapped Types",
    "https://www.typescriptlang.org/docs/handbook/2/mapped-types.html",
    "TypeScript",
    "en",
    "main",
    ["TypeScript"],
    22,
    "Преобразование свойств, modifiers и remapping ключей.",
  ),
  resource(
    "ts-narrowing",
    "Narrowing",
    "https://www.typescriptlang.org/docs/handbook/2/narrowing.html",
    "TypeScript",
    "en",
    "main",
    ["TypeScript"],
    30,
    "Type guards, discriminated unions, unknown и never.",
  ),
  resource(
    "ts-functions",
    "More on Functions",
    "https://www.typescriptlang.org/docs/handbook/2/functions.html",
    "TypeScript",
    "en",
    "deep-dive",
    ["TypeScript"],
    30,
    "Сигнатуры, перегрузки, unknown, never и вариантность параметров.",
  ),
  resource(
    "type-challenges",
    "Type Challenges",
    "https://github.com/type-challenges/type-challenges",
    "Type Challenges",
    "en",
    "practice",
    ["TypeScript"],
    40,
    "Большой набор задач на вывод и преобразование типов.",
  ),
  resource(
    "yandex-generics",
    "Продвинутые дженерики в TypeScript",
    "https://habr.com/ru/companies/yandex/articles/555520/",
    "Яндекс на Habr",
    "ru",
    "deep-dive",
    ["TypeScript"],
    14,
    "Русскоязычный доклад о вложенных generics, infer и сложных контрактах.",
    2021,
  ),
  resource(
    "yandex-typing",
    "Сага о типизации и тайпчекинге для JavaScript",
    "https://habr.com/ru/companies/yandex/articles/541338/",
    "Яндекс на Habr",
    "ru",
    "deep-dive",
    ["JavaScript", "TypeScript"],
    18,
    "Что TypeScript гарантирует, где заканчивается статическая проверка и зачем runtime-валидация.",
    2021,
  ),

  resource(
    "mdn-browser-work",
    "How browsers work",
    "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/How_browsers_work",
    "MDN",
    "en",
    "main",
    ["Browser", "Performance"],
    35,
    "Навигация, parsing, render tree, layout, paint и compositing.",
  ),
  resource(
    "mdn-crp",
    "Critical Rendering Path",
    "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Critical_rendering_path",
    "MDN",
    "en",
    "main",
    ["Browser", "Performance"],
    25,
    "Путь от HTML/CSS до первых пикселей и основные точки блокировки.",
  ),
  resource(
    "web-vitals",
    "Web Vitals",
    "https://web.dev/articles/vitals",
    "web.dev",
    "en",
    "main",
    ["Performance"],
    22,
    "Определения LCP, INP и CLS и пороги пользовательского опыта.",
  ),
  resource(
    "chrome-performance",
    "Performance panel reference",
    "https://developer.chrome.com/docs/devtools/performance/reference",
    "Chrome for Developers",
    "en",
    "practice",
    ["Browser", "Performance"],
    30,
    "Запись trace, main thread, network, layout shifts и поиск длинных задач.",
  ),
  resource(
    "developer-initial-load",
    "Initial load performance",
    "https://www.developerway.com/posts/initial-load-performance",
    "DeveloperWay",
    "en",
    "deep-dive",
    ["React", "Performance"],
    30,
    "Bundle, waterfalls, lazy loading и реальные ограничения первой загрузки React-приложения.",
  ),
  resource(
    "vk-speed",
    "Как мы в четыре раза ускорили мобильную версию ВКонтакте",
    "https://habr.com/ru/companies/vk/articles/811925/",
    "VK на Habr",
    "ru",
    "case-study",
    ["Performance", "React", "Browser"],
    12,
    "Свежий кейс измерения Web Vitals, удаления лишнего кода и оптимизации SPA.",
    2024,
  ),
  resource(
    "vk-performance",
    "Производительность фронтенда: важные метрики",
    "https://habr.com/ru/companies/vk/articles/454920/",
    "VK на Habr",
    "ru",
    "case-study",
    ["Performance", "Browser"],
    14,
    "Как связывать реальные пользовательские метрики с конкретной фазой приложения.",
    2019,
  ),
  resource(
    "mdn-cache",
    "HTTP caching",
    "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching",
    "MDN",
    "en",
    "main",
    ["Browser", "Performance"],
    30,
    "Cache-Control, ETag, revalidation, private/shared cache и cache busting.",
  ),
  resource(
    "web-resource-loading",
    "Optimize resource loading",
    "https://web.dev/learn/performance/optimize-resource-loading",
    "web.dev",
    "en",
    "main",
    ["Browser", "Performance"],
    22,
    "Приоритеты, preload, lazy loading и устранение сетевых блокировок.",
  ),
  resource(
    "web-virtualize",
    "Virtualize large lists",
    "https://web.dev/articles/virtualize-long-lists-react-window",
    "web.dev",
    "en",
    "main",
    ["React", "Performance"],
    20,
    "Windowing, recycling DOM nodes и ограничения fixed/variable lists.",
  ),
  resource(
    "mdn-http2",
    "HTTP/2",
    "https://developer.mozilla.org/en-US/docs/Glossary/HTTP_2",
    "MDN",
    "en",
    "reference",
    ["Browser"],
    12,
    "Мультиплексирование, streams и отличие от HTTP/1.1.",
  ),
  resource(
    "mdn-http3",
    "HTTP/3",
    "https://developer.mozilla.org/en-US/docs/Glossary/HTTP_3",
    "MDN",
    "en",
    "reference",
    ["Browser"],
    12,
    "QUIC, устранение TCP head-of-line blocking и быстрый handshake.",
  ),
  resource(
    "mdn-tls",
    "Transport Layer Security",
    "https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security",
    "MDN",
    "en",
    "reference",
    ["Browser", "Security"],
    22,
    "Цели TLS, сертификаты и безопасные настройки транспорта.",
  ),
  resource(
    "mdn-cors",
    "Cross-Origin Resource Sharing",
    "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CORS",
    "MDN",
    "en",
    "main",
    ["Browser", "Security"],
    30,
    "Simple requests, preflight, credentials и заголовки ответа.",
  ),
  resource(
    "mdn-cookies",
    "Using HTTP cookies",
    "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies",
    "MDN",
    "en",
    "main",
    ["Browser", "Security"],
    28,
    "Secure, HttpOnly, SameSite, область cookie и управление сессией.",
  ),
  resource(
    "web-css",
    "Learn CSS",
    "https://web.dev/learn/css",
    "web.dev",
    "en",
    "reference",
    ["CSS"],
    40,
    "Cascade, specificity, layout, Flexbox, Grid и responsive design.",
  ),
  resource(
    "wai-tutorials",
    "Web Accessibility Tutorials",
    "https://www.w3.org/WAI/tutorials/",
    "W3C WAI",
    "en",
    "main",
    ["Accessibility"],
    35,
    "Семантика, формы, таблицы, изображения и клавиатурная доступность.",
  ),
  resource(
    "wai-aria",
    "WAI-ARIA overview",
    "https://www.w3.org/WAI/standards-guidelines/aria/",
    "W3C WAI",
    "en",
    "reference",
    ["Accessibility"],
    20,
    "Когда нужна ARIA и почему нативная семантика предпочтительнее.",
  ),
  resource(
    "mdn-websocket",
    "WebSocket API",
    "https://developer.mozilla.org/en-US/docs/Web/API/WebSocket",
    "MDN",
    "en",
    "main",
    ["Browser", "Architecture"],
    24,
    "Двунаправленное соединение, события, backpressure и закрытие канала.",
  ),
  resource(
    "mdn-sse",
    "Server-sent events",
    "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events",
    "MDN",
    "en",
    "main",
    ["Browser", "Architecture"],
    20,
    "Однонаправленный поток событий поверх HTTP и автоматический reconnect.",
  ),
  resource(
    "mdn-service-worker",
    "Service Worker API",
    "https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API",
    "MDN",
    "en",
    "main",
    ["Browser", "Architecture"],
    35,
    "Перехват запросов, offline cache, lifecycle и ограничения worker-контекста.",
  ),
  resource(
    "tanstack-optimistic",
    "Optimistic updates",
    "https://tanstack.com/query/latest/docs/framework/react/guides/optimistic-updates",
    "TanStack",
    "en",
    "main",
    ["React", "Architecture"],
    20,
    "Оптимистичное состояние, rollback и согласование с server state.",
  ),

  resource(
    "patterns-dev",
    "Patterns.dev",
    "https://www.patterns.dev/",
    "Patterns.dev",
    "en",
    "reference",
    ["Architecture", "JavaScript", "React"],
    40,
    "Каталог проектных и производительных паттернов для современных веб-приложений.",
  ),
  resource(
    "yandex-solid",
    "Пишем переиспользуемые компоненты, соблюдая SOLID",
    "https://habr.com/ru/companies/yandex/articles/560194/",
    "Яндекс на Habr",
    "ru",
    "case-study",
    ["Architecture", "React", "TypeScript"],
    21,
    "SOLID на конкретных React + TypeScript компонентах и контрактах.",
    2021,
  ),
  resource(
    "fsd-overview",
    "Feature-Sliced Design overview",
    "https://fsd.how/docs/get-started/overview/",
    "Feature-Sliced Design",
    "en",
    "main",
    ["Architecture"],
    20,
    "Назначение методологии, slices, segments и публичные API модулей.",
  ),
  resource(
    "fsd-layers",
    "Feature-Sliced Design layers",
    "https://fsd.how/docs/reference/layers/",
    "Feature-Sliced Design",
    "en",
    "main",
    ["Architecture"],
    25,
    "Ответственность слоёв и правило направленности зависимостей.",
  ),
  resource(
    "nx-monorepo",
    "Nx monorepo concepts",
    "https://nx.dev/docs/getting-started/intro",
    "Nx",
    "en",
    "main",
    ["Architecture"],
    25,
    "Граф проекта, affected-команды, кэширование и границы пакетов монорепы.",
  ),
  resource(
    "martin-microfrontends",
    "Micro Frontends",
    "https://martinfowler.com/articles/micro-frontends.html",
    "Martin Fowler",
    "en",
    "deep-dive",
    ["Architecture"],
    35,
    "Мотивация, интеграция, независимые релизы и организационная цена подхода.",
    2019,
  ),
  resource(
    "avito-microfrontends",
    "Микрофронтенды в SSR: опыт Авито",
    "https://habr.com/ru/companies/avito/articles/778582/",
    "AvitoTech на Habr",
    "ru",
    "case-study",
    ["Architecture", "React"],
    12,
    "Промышленный кейс миграции микрофронтендов и поддержки SSR.",
    2023,
  ),
  resource(
    "yandex-frontend-architecture",
    "Верхнеуровневая архитектура фронтенда",
    "https://habr.com/ru/companies/yandex/articles/425611/",
    "Яндекс на Habr",
    "ru",
    "deep-dive",
    ["Architecture"],
    25,
    "Лекция о компонентной архитектуре, MV*, Flux и потоке данных.",
    2018,
  ),
  resource(
    "avito-system-design",
    "Готовимся к System Design Interview",
    "https://habr.com/ru/companies/avito/articles/753248/",
    "AvitoTech на Habr",
    "ru",
    "main",
    ["Architecture", "Interview"],
    12,
    "Пошаговая структура frontend system design секции и ожидаемые trade-offs.",
    2023,
  ),
  resource(
    "yandex-prep",
    "Подготовка frontend-разработчика",
    "https://yandex.ru/jobs/services/hr-tech/frontend",
    "Яндекс",
    "ru",
    "main",
    ["Interview"],
    20,
    "Официальные ожидания Яндекса и рекомендованные материалы по фронтенду.",
  ),
  resource(
    "yandex-interview",
    "Frontend-интервью в Яндексе",
    "https://yandex.ru/yaintern/frontend/interview",
    "Яндекс",
    "ru",
    "main",
    ["Interview"],
    15,
    "Этапы интервью, формат задач и критерии успешного решения.",
  ),
  resource(
    "yandex-lectures",
    "22 лекции по разработке интерфейсов",
    "https://education.yandex.ru/journal/22-videolektsii-po-razrabotke-interfejsov",
    "Яндекс Образование",
    "ru",
    "reference",
    ["JavaScript", "Browser", "Architecture", "Interview"],
    45,
    "Большой русскоязычный набор лекций ШРИ для закрытия точечных пробелов.",
  ),
  resource(
    "frontend-handbook",
    "Front End Interview Handbook",
    "https://github.com/yangshun/front-end-interview-handbook",
    "Front End Interview Handbook",
    "en",
    "reference",
    ["Interview", "JavaScript", "React", "Browser"],
    45,
    "Актуальный каталог вопросов, форматов интервью и чек-листов подготовки.",
  ),
  resource(
    "avito-strong-frontend",
    "Как стать по-настоящему классным фронтендером",
    "https://habr.com/ru/companies/avito/articles/774696/",
    "AvitoTech на Habr",
    "ru",
    "case-study",
    ["Interview", "Architecture"],
    14,
    "Ожидания по платформе, алгоритмам, проектированию и развитию инженерного кругозора.",
    2023,
  ),
  resource(
    "yandex-algo-interview",
    "Как проходят алгоритмические секции в Яндексе",
    "https://habr.com/ru/companies/yandex/articles/449890/",
    "Яндекс на Habr",
    "ru",
    "case-study",
    ["Algorithms", "Interview"],
    12,
    "Официальный рассказ о ходе секции, коммуникации и оценке решения.",
    2019,
  ),
  resource(
    "avito-algo-tips",
    "На что обращать внимание на алгоритмических секциях",
    "https://habr.com/ru/companies/avito/articles/662922/",
    "AvitoTech на Habr",
    "ru",
    "case-study",
    ["Algorithms", "Interview"],
    8,
    "Тайминг, проговаривание решения, тестирование и типичные ошибки кандидатов.",
    2022,
  ),
  resource(
    "testing-library",
    "React Testing Library",
    "https://testing-library.com/docs/react-testing-library/intro/",
    "Testing Library",
    "en",
    "main",
    ["Testing", "React"],
    25,
    "Тестирование поведения компонента через доступные пользователю DOM-элементы.",
  ),
  resource(
    "vitest",
    "Vitest Guide",
    "https://vitest.dev/guide/index.html",
    "Vitest",
    "en",
    "main",
    ["Testing", "JavaScript", "TypeScript"],
    25,
    "Test runner, assertions, mocks и интеграция с Vite.",
  ),
  resource(
    "playwright",
    "Playwright",
    "https://playwright.dev/docs/intro",
    "Playwright",
    "en",
    "main",
    ["Testing", "Browser"],
    25,
    "E2E-тесты, browser contexts, локаторы, trace и мобильная эмуляция.",
  ),
  resource(
    "owasp-xss",
    "Cross Site Scripting Prevention",
    "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html",
    "OWASP",
    "en",
    "main",
    ["Security", "Browser"],
    30,
    "Контексты вывода, escaping, sanitization и опасные DOM sinks.",
  ),
  resource(
    "owasp-csrf",
    "Cross-Site Request Forgery Prevention",
    "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html",
    "OWASP",
    "en",
    "main",
    ["Security", "Browser"],
    28,
    "CSRF tokens, SameSite, Fetch Metadata и защита state-changing запросов.",
  ),
  resource(
    "owasp-csp",
    "Content Security Policy",
    "https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html",
    "OWASP",
    "en",
    "main",
    ["Security", "Browser"],
    30,
    "Строгая CSP, nonce/hash, report-only и защита в глубину от XSS.",
  ),
];

const RESOURCE_TOPICS = new Set<ResourceTopic>([
  "JavaScript",
  "React",
  "TypeScript",
  "Algorithms",
  "Browser",
  "Performance",
  "CSS",
  "Accessibility",
  "Architecture",
  "Testing",
  "Security",
  "Interview",
]);

const RESOURCE_URL_ALIASES = new Map([
  [
    "https://feature-sliced.design/docs/get-started/overview",
    "https://fsd.how/docs/get-started/overview",
  ],
]);

const normalizeResourceUrl = (url: string) =>
  url.replace(/\/index\.html$/, "").replace(/\/$/, "");

const getCanonicalResourceUrl = (url: string) => {
  const normalizedUrl = normalizeResourceUrl(url);
  return RESOURCE_URL_ALIASES.get(normalizedUrl) ?? normalizedUrl;
};

const getResearchTopics = (topics: string[]): ResourceTopic[] =>
  topics.filter((topic): topic is ResourceTopic => RESOURCE_TOPICS.has(topic as ResourceTopic));

const resourcesByUrl = new Map(
  BASE_RESOURCES.map((item) => [getCanonicalResourceUrl(item.url), item] as const),
);

for (const researchResource of RESEARCH_RESOURCES) {
  const canonicalUrl = getCanonicalResourceUrl(researchResource.url);
  const existingResource = resourcesByUrl.get(canonicalUrl);
  const { tags, topics, ...researchMetadata } = researchResource;
  const mappedTopics = getResearchTopics(topics);

  resourcesByUrl.set(canonicalUrl, {
    ...existingResource,
    ...researchMetadata,
    id: existingResource?.id ?? researchResource.id,
    title: existingResource?.title ?? researchResource.title,
    topics: [...new Set([...(existingResource?.topics ?? []), ...mappedTopics])],
    tags,
  });
}

export const RESOURCES: LearningResource[] = [...resourcesByUrl.values()];

export const RESOURCE_PLANS: WeekResourcePlan[] = [
  {
    theory: [
      ["js-execution-model", "ydkjs"],
      ["js-types", "js-comparisons"],
      ["js-var", "js-closure"],
      ["js-event-loop", "mdn-microtask-guide", "js-event-loop-deep"],
      ["js-event-loop", "js-async-habr"],
      ["js-memory", "js-memory-mdn"],
      ["learn-js", "mdn-js-guide"],
    ],
    practice: [
      ["js-event-loop", "js-async-habr"],
      ["yandex-algorithms", "hello-algo"],
      ["leetcode-two-sum"],
      ["leetcode-group-anagrams"],
      ["developer-debounce"],
      ["structured-clone", "js-memory"],
      ["yandex-prep", "frontend-handbook"],
    ],
  },
  {
    theory: [
      ["js-closure", "ydkjs"],
      ["js-this", "ydkjs"],
      ["js-call-apply", "js-bind"],
      ["js-prototype", "ydkjs"],
      ["js-class", "js-prototype"],
      ["js-currying", "js-call-apply"],
      ["js-closure", "js-memory-mdn"],
    ],
    practice: [
      ["js-var", "js-closure"],
      ["js-bind", "js-call-apply"],
      ["js-currying"],
      ["hello-algo", "yandex-algorithms", "leetcode-two-sum-ii"],
      ["leetcode-longest-substring"],
      ["leetcode-min-window"],
      ["frontend-handbook", "yandex-prep"],
    ],
  },
  {
    theory: [
      ["js-promises", "js-promise-api", "learnjs-async"],
      ["js-async-await", "js-async-habr"],
      ["js-promise-api", "js-async-habr"],
      ["js-fetch-abort", "mdn-abortcontroller", "developer-fetch"],
      ["js-generators", "js-iterables"],
      ["hello-algo", "hello-algo-binary-search", "yandex-algorithms"],
      ["hello-algo", "yandex-algorithms"],
    ],
    practice: [
      ["js-promise-api", "js-promises"],
      ["js-promise-api"],
      ["js-promise-api", "js-fetch-abort"],
      ["leetcode-valid-parentheses"],
      ["leetcode-queue-stacks"],
      ["leetcode-first-last", "hello-algo-binary-search"],
      ["yandex-prep", "frontend-handbook"],
    ],
  },
  {
    theory: [
      ["react-preserving-state", "developer-reconciliation"],
      ["developer-key", "react-preserving-state"],
      ["react-fiber", "developer-reconciliation"],
      ["react-render-commit", "react-fiber"],
      ["react-queue-state", "developer-rerenders"],
      ["react-transition", "react-fiber"],
      ["react-compiler", "reactdev-react-compiler-1", "yandex-react-performance"],
    ],
    practice: [
      ["developer-key", "react-preserving-state"],
      ["developer-rerenders", "react-devtools"],
      ["react-fiber"],
      ["react-render-commit"],
      ["react-queue-state", "react-devtools"],
      ["react-transition"],
      ["frontend-handbook", "yandex-prep"],
    ],
  },
  {
    theory: [
      ["react-rules-hooks", "react-render-commit"],
      ["react-effect-lifecycle", "react-remove-deps"],
      ["developer-stale", "js-closure"],
      ["developer-memo", "react-compiler"],
      ["developer-context", "developer-rerenders"],
      ["tanstack-query", "redux-style", "zustand"],
      ["developer-custom-hooks", "react-rules-hooks"],
    ],
    practice: [
      ["react-rules-hooks"],
      ["react-remove-deps", "react-no-effect"],
      ["developer-stale"],
      ["developer-memo", "react-devtools"],
      ["developer-context"],
      ["tanstack-query", "redux-style", "zustand"],
      ["developer-custom-hooks", "testing-library"],
    ],
  },
  {
    theory: [
      ["ts-generics", "yandex-generics"],
      ["ts-conditional", "yandex-generics"],
      ["ts-mapped", "type-challenges"],
      ["ts-narrowing", "yandex-typing"],
      ["ts-narrowing", "ts-functions"],
      ["ts-functions", "yandex-typing"],
      ["hello-algo", "yandex-algorithms"],
    ],
    practice: [
      ["ts-generics", "type-challenges-warmup", "type-challenges-pick", "type-challenges"],
      ["ts-conditional", "type-challenges-readonly", "type-challenges"],
      ["ts-mapped", "type-challenges"],
      ["ts-narrowing", "type-challenges"],
      ["ts-narrowing", "yandex-typing"],
      ["ts-functions", "yandex-generics"],
      ["hello-algo", "yandex-algorithms"],
    ],
  },
  {
    theory: [
      ["mdn-crp", "mdn-browser-work"],
      ["mdn-browser-work", "chrome-performance"],
      ["web-vitals", "webdev-cwv-thresholds", "vk-speed"],
      ["web-resource-loading", "developer-initial-load"],
      ["web-virtualize", "developer-rerenders"],
      ["mdn-cache", "web-resource-loading"],
      ["hello-algo", "yandex-algorithms"],
    ],
    practice: [
      ["mdn-crp", "chrome-performance"],
      ["mdn-browser-work", "chrome-performance", "sber-perf-devtools"],
      ["web-vitals", "vk-speed", "vk-performance"],
      ["developer-initial-load", "web-resource-loading"],
      ["web-virtualize"],
      ["mdn-cache"],
      ["leetcode-climbing-stairs", "leetcode-max-subarray"],
    ],
  },
  {
    theory: [
      ["mdn-http2", "mdn-http3", "mdn-tls"],
      ["mdn-cors", "mdn-cookies"],
      ["web-css"],
      ["wai-tutorials", "wai-aria"],
      ["avito-system-design", "feh-system-design", "web-virtualize"],
      ["mdn-websocket", "mdn-sse"],
      ["mdn-service-worker", "tanstack-optimistic"],
    ],
    practice: [
      ["chrome-performance", "mdn-http2"],
      ["mdn-cookies", "owasp-csrf"],
      ["web-css"],
      ["wai-tutorials", "wai-aria"],
      ["avito-system-design", "greatfrontend-radio", "web-virtualize"],
      ["mdn-websocket", "mdn-sse"],
      ["mdn-service-worker", "tanstack-optimistic"],
    ],
  },
  {
    theory: [
      ["yandex-solid", "patterns-dev"],
      ["developer-composition", "developer-component-prop", "avito-components"],
      ["fsd-overview", "fsd-layers", "vk-fsd"],
      ["nx-monorepo", "nx-dev-monorepo", "yandex-frontend-architecture"],
      ["martin-microfrontends", "avito-microfrontends", "ozon-microfrontend"],
      ["frontend-handbook", "avito-strong-frontend", "wb-head-frontend-interview"],
      ["yandex-prep", "frontend-handbook"],
    ],
    practice: [
      ["yandex-solid", "patterns-dev"],
      ["yandex-frontend-architecture", "avito-components"],
      ["fsd-layers"],
      ["nx-monorepo"],
      ["martin-microfrontends", "avito-microfrontends"],
      ["frontend-handbook", "avito-strong-frontend"],
      ["yandex-prep", "frontend-handbook"],
    ],
  },
  {
    theory: [
      ["yandex-prep", "yandex-frontend-interview", "tbank-interview", "frontend-handbook"],
      ["avito-algo-tips", "yandex-interview", "sber-frontend-interview", "avito-playbook-hiring"],
      ["avito-system-design", "feh-system-design", "greatfrontend-radio"],
      ["frontend-handbook", "avito-strong-frontend"],
      ["yandex-prep", "frontend-handbook"],
      ["yandex-prep", "avito-strong-frontend"],
      ["frontend-handbook", "yandex-lectures"],
    ],
    practice: [
      ["yandex-prep", "frontend-handbook"],
      ["react-devtools", "mdn-browser-work"],
      ["leetcode-plan", "yandex-algo-interview", "avito-algo-tips"],
      ["avito-system-design"],
      ["yandex-interview", "frontend-handbook"],
      ["yandex-prep", "avito-strong-frontend"],
      ["yandex-interview", "frontend-handbook"],
    ],
  },
  {
    theory: [
      ["yandex-prep", "frontend-handbook"],
      ["learn-js", "js-async-habr"],
      ["react-render-commit", "developer-rerenders"],
      ["ts-narrowing", "mdn-browser-work"],
      ["hello-algo", "leetcode-plan"],
      ["avito-system-design", "patterns-dev"],
      ["testing-library", "testing-library-guiding", "owasp-xss", "owasp-csp"],
    ],
    practice: [
      ["yandex-prep", "frontend-handbook"],
      ["learn-js", "frontend-handbook"],
      ["react-devtools", "developer-rerenders"],
      ["type-challenges", "chrome-performance"],
      ["leetcode-plan", "yandex-algorithms"],
      ["avito-system-design"],
      [
        "vitest",
        "vitest-browser-mode",
        "testing-library",
        "playwright",
        "playwright-writing-tests",
      ],
    ],
  },
  {
    theory: [
      ["yandex-interview", "frontend-handbook"],
      ["js-async-habr", "react-fiber", "react-render-commit"],
      ["hello-algo", "leetcode-plan"],
      ["patterns-dev", "avito-system-design"],
      ["avito-strong-frontend", "yandex-prep"],
      ["yandex-prep", "frontend-handbook"],
      ["yandex-lectures", "frontend-handbook"],
    ],
    practice: [
      ["yandex-interview", "frontend-handbook"],
      ["js-event-loop", "react-render-commit"],
      ["leetcode-plan", "avito-algo-tips"],
      ["avito-system-design"],
      ["avito-strong-frontend", "yandex-prep"],
      ["frontend-handbook", "yandex-prep"],
      ["yandex-interview", "frontend-handbook"],
    ],
  },
];

export const RESOURCE_IDS = new Set(RESOURCES.map((item) => item.id));

export function getResourceIdsForBlock(
  weekIndex: number,
  dayIndex: number,
  kind: "theory" | "practice",
) {
  const weekPlan = RESOURCE_PLANS[weekIndex];
  const resourceIds = weekPlan?.[kind][dayIndex];
  return resourceIds ? [...resourceIds] : [];
}
